# NUMPY: Leer y escribir archivos txt

**numpy.genfromtxt():** Esta función es una herramienta versátil para leer datos de archivos de texto. Puede manejar archivos con valores faltantes, encabezados y diferentes tipos de datos. Algunas características clave de genfromtxt() son:

Puede manejar archivos con formatos de valores separados por comas, espacios, tabulaciones u otros delimitadores personalizados.

-Puede omitir filas o columnas específicas.

-Permite especificar el tipo de datos de cada columna o inferir automáticamente los tipos de datos.
-Admite el manejo de valores faltantes, proporcionando opciones para rellenarlos o ignorarlos.

In [ ]:
import numpy as np
data = np.genfromtxt('archivo.txt', delimiter=',')
data = np.genfromtxt('archivo.csv', delimiter=',')


**numpy.savetxt():** Esta función se utiliza para guardar una matriz NumPy en un archivo de texto. Puedes especificar el delimitador y otras opciones para formatear los datos guardados.

In [ ]:
# Escribir en un archivo de texto un array (4x5) generado
# con números aleatorios del 1 al 10:
import numpy as np
a = np.random.randint(1, 11, (4,5))
print(a)



[[10  8  6  9  6]
 [10  1  2  3  1]
 [ 1  5  5  5  2]
 [10  9  1  9  6]]


In [ ]:
np.savetxt('datos_sala1.txt', a)

**numpy.loadtxt():** Esta función es similar a genfromtxt() pero más limitada en cuanto a funcionalidad. loadtxt() se utiliza para cargar matrices NumPy a partir de archivos de texto, pero no admite características avanzadas como encabezados o valores faltantes. Es útil para cargar archivos de texto simples con datos numéricos sin complicaciones.

In [ ]:
# Leer los datos de un archivo de texto y declarar un array:

a = np.loadtxt('datos_prueba.txt',delimiter=' ')
print(a)

[22. 33. 44. 55. 66. 77. 88. 99.  0. 11.]


In [ ]:
nombres = np.loadtxt('nombres.txt', dtype=str)

print(nombres)

['marcos' 'maria' 'jose' 'ariel' 'josefina' 'carlos' 'walter']


EJERCICIO: Crear un archivo txt llamado dias_semana que
contenga los días de la semana y leerlo.





EJERCICIO: Crear un archivo .txt con los datos de las temperaturas minimas esta semana y leerlos y mostralas las temperaturas con el dia correspondiente.
Por ejemplo lunes 12° martes 4° ....

In [ ]:
a = np.loadtxt('dias_semana.txt', dtype=str)
b = np.loadtxt('temperaturas_minimas.txt', dtype=str)

for dia, temperatura in zip(a, b):
 print(f'{dia} {temperatura}°')

Lunes 2°
Martes 2°
Miércoles 6°
Jueves 7°
Viernes 6°
Sábado 4°
Domingo 8°
