<a href="https://colab.research.google.com/github/gagabriela2787/csdedatos/blob/main/numpyej.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

Proceso de instalación


Creacion de arreglos a partir de listas


Con numeros prefijados


Con numeros aleatorios

In [2]:
#importar numpy
import numpy as np


In [3]:
#crear un arreglo unidimesional
arreglo1=np.array([1,2,3,4,5])
print(arreglo1)

[1 2 3 4 5]


In [4]:
#crear arreglo de dos dimensiones
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [5]:
arreglo3=np.array([matrix, matrix])
print(arreglo3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
#uso de arange
a=np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


Ejercicio:
Crear una matriz de 3 filas y 5 columnas,

 completados con los numeros del 1 al 15.


In [ ]:
matriz = np.arange(1, 10).reshape(3, 3)
print(matriz)

In [ ]:
# creando un arreglo con 0
arreglo=np.zeros((3,5))
print(arreglo)

In [ ]:
# hacer lo mismo pero con una matriz

In [ ]:
#creando un arreglo con 1
arreglo=np.ones(10)
print(arreglo)

In [ ]:
#creando un arreglo con un mismo numero
arreglo=np.full(10,6)
print(arreglo)

In [ ]:
#Crear un arreglo con valores uniformemente espaciados
arreglo=np.linspace(15, 20, 7)
print(arreglo)

Crear un matrix de 4 filas y 5 columnas




, lleno completamente del mismo valor 5.


# Numeros aleatorios con NumPy

In [ ]:
# generar arreglo con nros enteros valor inicial,valor final, tamaño
x = np.random.randint(0,100,size=25)

print(x)


In [ ]:
#nros aleatorios entre 0 y 1
b=np.random.rand(3)
print(b)

Crear un arreglo tipo matriz de 3 filas y 7 columnas con numeros aleatorios entre 5 y 6.

# Operando sobre arreglos

In [ ]:
a=np.array([1,2,3,4,5])

b=a**3

print(b)

In [ ]:
#podemos operar vectorialmente, siempre que sean de las mismos tamaños
c=np.array([6,7,8,9,10])

d=a+c

print(d)